name: Deploy to Databricks


on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install databricks-cli

      - name: Configure Databricks CLI
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          mkdir -p ~/.databricks
          echo "[DEFAULT]" > ~/.databrickscfg
          echo "host=$DATABRICKS_HOST" >> ~/.databrickscfg
          echo "token=$DATABRICKS_TOKEN" >> ~/.databrickscfg

      - name: Deploy Source Code
        run: |
          databricks workspace import_dir taf_jan_march_2026 /Shared/taf_jan_march_2026 --overwrite

      - name: Run Databricks Job
        run: |
          databricks jobs run-now --job-id 228463018371850